# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-07 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('device_key', models.CharField(max_length=150)),
                ('tem', models.CharField(max_length=150)),
                ('hum', models.CharField(max_length=150)),
                ('bright', models.CharField(max_length=150)),
                ('door_status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
